
[secrets]
folder = "${TEST_DB_DIR}/secrets"

[knowledge-base]
knowledge-base-root-folder = "${TEST_DB_DIR}/knowledge-base/envs/2011_ENV/kb"
external-collaboration-folder = "${TEST_DB_DIR}/knowledge-base/envs/2011_ENV/external-collaboration"

[organization-settings]
month-fiscal-year-starts = 6
organization = "Intuit"
knowledge-base-areas = ["Production", "Innovations"]

[cli]
initializer-classname = "apodeixi.cli.kb_session.KB_Session_Initializer"

[backward-compabitility]
grandfathered_scoring_cycles   = ["Dec 2020", "FY 21 - 9+3", "March 2021"]

