1002_ENV:
  METADATA.yaml: '

    Size (in bytes):  503

    '
  external-collaboration:
    admin:
      static-data:
        _ARCHIVE:
          (Timestamp omitted) Form Request:
            FORM_REQUEST_EVENT_LOG.txt: '

              Size (in bytes):  316

              '
          (Timestamp omitted) Posting:
            POST_EVENT_LOG.txt: '

              Size (in bytes):  1650

              '
            products.static-data.admin.a6i.xlsx: '

              Size (in bytes):  7147

              '
        products.static-data.admin.a6i.xlsx: '

          Size (in bytes):  7046

          '
  kb:
    excel-postings:
      admin:
        static-data:
          _ARCHIVE:
            (Timestamp omitted) Form Request:
              FORM_REQUEST_EVENT_LOG.txt: '

                Size (in bytes):  316

                '
            (Timestamp omitted) Posting:
              POST_EVENT_LOG.txt: '

                Size (in bytes):  1650

                '
              products.static-data.admin.a6i.xlsx: '

                Size (in bytes):  7147

                '
          products.static-data.admin.a6i.xlsx: '

            Size (in bytes):  7147

            '
    manifests:
      my-corp.testing-area:
        static-data:
          line-of-business.1.yaml: '

            Size (in bytes):  786

            '
          product.1.yaml: '

            Size (in bytes):  1025

            '
