apiVersion: static-data.admin.a6i.io/v1a
assertion:
  entity_type: product
  estimatedBy: accountableowner.lastname@your_company.com
  estimatedOn: &id001 2021-08-04 00:00:00
  product:
    P1:
      Alias names: My Product A, My product A, myprod A
      UID: P1
      lineOfBusiness: LOB1
      name: MYPROD_A
    P1-name: MYPROD_A
    P2:
      Alias names: My Product B, My product B, myprod B
      UID: P2
      lineOfBusiness: LOB2
      name: MYPROD_B
    P2-name: MYPROD_B
    P3:
      Alias names: My Product C, My product C, myprod C
      UID: P3
      lineOfBusiness: LOB2
      name: MYPROD_C
    P3-name: MYPROD_C
  recordedBy: yourname.lastname@your_company.com
kind: product
metadata:
  labels:
    estimatedBy: accountableowner.lastname@your_company.com
    estimatedOn: *id001
    knowledgeBase: Testing Area
    organization: My Corp
    recordedBy: yourname.lastname@your_company.com
    version: 1
  name: static-data
  namespace: my-corp.testing-area
  version: 1
