1002_ENV:
  external-collaboration:
    admin:
      static-data:
        _ARCHIVE:
          (Timestamp omitted) Posting:
            FORM_REQUEST_EVENT_LOG.txt: '

              Size (in bytes):  335

              '
            POST_EVENT_LOG.txt: '

              Size (in bytes):  1669

              '
            products.static-data.admin.a6i.xlsx: '

              Size (in bytes):  7127

              '
    journeys:
      Dec 2020:
        FusionOpus:
          Default:
            OPUS_big-rocks.journeys.a6i.xlsx: '

              Size (in bytes):  25146

              '
        LedgerPro:
          OfficialPlan:
            LedgerPro.big-rocks.journeys.a6i.xlsx: '

              Size (in bytes):  28512

              '
  kb:
    excel-postings:
      admin:
        static-data:
          _ARCHIVE:
            (Timestamp omitted) Posting:
              FORM_REQUEST_EVENT_LOG.txt: '

                Size (in bytes):  335

                '
              POST_EVENT_LOG.txt: '

                Size (in bytes):  1669

                '
              products.static-data.admin.a6i.xlsx: '

                Size (in bytes):  7127

                '
          products.static-data.admin.a6i.xlsx: '

            Size (in bytes):  7127

            '
    manifests:
      my-corp.testing-area:
        static-data:
          line-of-business.1.yaml: '

            Size (in bytes):  786

            '
          product.1.yaml: '

            Size (in bytes):  1025

            '
