1002_ENV:
  external-collaboration:
    admin:
      static-data:
        _ARCHIVE:
          (Timestamp omitted) Posting:
            FORM_REQUEST_EVENT_LOG.txt: '

              Size (in bytes):  335

              '
        products.static-data.admin.a6i.xlsx: '

          Size (in bytes):  7147

          '
  kb:
    excel-postings:
      admin:
        static-data:
          _ARCHIVE:
            (Timestamp omitted) Posting:
              FORM_REQUEST_EVENT_LOG.txt: '

                Size (in bytes):  335

                '
