static_data_flows.products.products_ENV:
  external-collaboration:
    admin:
      static-data:
        _ARCHIVE:
          (Timestamp omitted) Posting:
            FORM_REQUEST_EVENT_LOG.txt: '

              Size (in bytes):  366

              '
        products.static-data.admin.a6i.xlsx: '

          Size (in bytes):  7128

          '
    journeys:
      Dec 2020:
        FusionOpus:
          Default:
            OPUS_big-rocks.journeys.a6i.xlsx: '

              Size (in bytes):  25146

              '
        LedgerPro:
          OfficialPlan:
            LedgerPro.big-rocks.journeys.a6i.xlsx: '

              Size (in bytes):  28512

              '
  kb:
    excel-postings:
      admin:
        static-data:
          _ARCHIVE:
            (Timestamp omitted) Posting:
              FORM_REQUEST_EVENT_LOG.txt: '

                Size (in bytes):  366

                '
