1002_ENV:
  external-collaboration:
    admin:
      static-data:
        _ARCHIVE:
          (Timestamp omitted) Posting:
            FORM_REQUEST_EVENT_LOG.txt: '

              Size (in bytes):  335

              '
            POST_EVENT_LOG.txt: '

              Size (in bytes):  1669

              '
            products.static-data.admin.a6i.xlsx: '

              Size (in bytes):  7147

              '
        products.static-data.admin.a6i.xlsx: '

          Size (in bytes):  7045

          '
  kb:
    excel-postings:
      admin:
        static-data:
          _ARCHIVE:
            (Timestamp omitted) Posting:
              FORM_REQUEST_EVENT_LOG.txt: '

                Size (in bytes):  335

                '
              POST_EVENT_LOG.txt: '

                Size (in bytes):  1669

                '
              products.static-data.admin.a6i.xlsx: '

                Size (in bytes):  7147

                '
          products.static-data.admin.a6i.xlsx: '

            Size (in bytes):  7147

            '
    manifests:
      my-corp.testing-area:
        static-data:
          line-of-business.1.yaml: '

            Size (in bytes):  786

            '
          product.1.yaml: '

            Size (in bytes):  1025

            '
