
[secrets]
folder = "${TEST_DB_DIR}/secrets"

[knowledge-base]
knowledge-base-root-folder = "${TEST_DB_DIR}/knowledge-base/envs/4011_ENV/kb"
external-collaboration-folder = "${TEST_DB_DIR}/knowledge-base/envs/4011_ENV/external-collaboration"

[organization-settings]
month-fiscal-year-starts = 6
organization = "Cicloquimica"
knowledge-base-areas = ["Production", "Testing Area"]

[cli]
initializer-classname = "apodeixi.cli.kb_session.KB_Session_Initializer"

[backward-compabitility]
grandfathered_scoring_cycles   = [""]
