
[secrets]
folder = "C:/Alex/Code/ea-journeys/secrets"

[knowledge-base]
knowledge-base-root-folder = "C:/Users/aleja/Documents/Code/chateauclaudia-labs/apodeixi/test_db/knowledge-base/envs/8002_ENV/kb"
external-collaboration-folder = "C:/Users/aleja/Documents/Code/chateauclaudia-labs/apodeixi/test_db/knowledge-base/envs/8002_ENV/external-collaboration"

#knowledge-base-root-folder = "C:/Users/aleja/tmp/tmp_test_Db/knowledge-base"
#external-collaboration-folder = "C:/Users/aleja/tmp/tmp_test_Db/share-point"

[organization-settings]
month-fiscal-year-starts = 6
organization = "My Corp"
knowledge-base-areas = ["Production", "Testing Area"]

[cli]
initializer-classname = "apodeixi.cli.kb_session.KB_Session_Initializer"

